packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': 2.0.9
  '@acdh-oeaw/eslint-config-next': ^2.0.21
  '@acdh-oeaw/eslint-config-node': 2.0.9
  '@acdh-oeaw/eslint-config-playwright': ^2.0.10
  '@acdh-oeaw/eslint-config-react': ^2.0.13
  '@acdh-oeaw/eslint-config-tailwindcss': ^3.0.1
  '@acdh-oeaw/lib': 0.3.4
  '@acdh-oeaw/prettier-config': 2.0.1
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/tsconfig-lib': ^1.3.0
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.6
  '@keystatic/core': ^0.5.48
  '@keystatic/next': ^5.0.4
  '@mdx-js/mdx': ^3.1.0
  '@parcel/watcher': ^2.5.1
  '@playwright/test': ^1.54.2
  '@tailwindcss/postcss': ^4.1.12
  '@types/mdx': ^2.0.13
  '@types/node': ^22.17.2
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  concurrently: 9.2.0
  devalue: ^5.1.1
  dotenv-cli: 10.0.0
  es-module-lexer: ^1.7.0
  eslint: 9.33.0
  eslint-config-flat-gitignore: 2.1.0
  globals: 16.3.0
  is-in-ci: ^1.0.0
  lint-staged: ^16.1.5
  next: 15.4.2-canary.44
  node: ^22.18.0
  npm-run-all2: 8.0.4
  p-limit: ^7.0.0
  prettier: 3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.12
  to-vfile: ^8.0.0
  tsdown: ^0.14.1
  tsx: 4.20.4
  turbo: ^2.5.6
  typescript: ^5.9.2
  typescript-eslint: 8.39.1
  valibot: 1.1.0
  vfile: ^6.0.3
  vfile-matter: ^5.0.1

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - unrs-resolver
